behaviors:
  CarDriving:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 25600
      learning_rate: 0.001
      beta: 0.005
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
    keep_checkpoints: 10
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 50000
